### PR TITLE
Tweak CSS to align settings better (issue #829)

### PR DESCRIPTION
**Pull request by IBBoard**
Minor tweak to fix issue #829 - pad the labels and then shift the checkboxes left with negative margins

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Could you post a screen shot?

**Comment by IBBoard** [comment]
ocnews_alignmentfix

**Comment by IBBoard** [comment]
I tweaked it slightly to align as closely as I can.
ocnews_alignmentfix_2
ocnews_alignmentfix_zoomed

**Comment by BernhardPosselt** [comment]
Awesome I think that fixes the issue :)

thanks!

**Pull request merged**
