### PR TITLE
fix width of article action icon slot

### PR DESCRIPTION
**Pull request by cosenal**
Before: 
article-actions-before

After:
article-actions-after

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Is the BG image quadratic?

**Comment by cosenal** [comment]
@BernhardPosselt same size as the eye and star icons

**Comment by BernhardPosselt** [comment]
Ok, looks good then, can you also run grunt?

**Comment by cosenal** [comment]
already run, I didn't uglify manually :)

**Pull request merged**
