### PR TITLE
New starred icon on mouse-hover

### PR DESCRIPTION
**Pull request by bbBowser**
Like described in this issue https://github.com/owncloud/news/issues/949, i tried changing it myself.

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Awesome thanks, however I can barely see the difference on my 1080p Monitor, the boarder is too thin and low contrast I think.

**Comment by BernhardPosselt** [comment]
Not saying that the border/contrast should be the only solution to this problem, there are also gradients, shadows etc :)

**Comment by bbBowser** [comment]
I did not want to mess around to much with the overall look, i'm not a artist :D

**Comment by BernhardPosselt** [comment]
Neither am I ;D 

If I'm firing up inkscape, I'm taking as little time as possible, therefore most icons are not that well designed ;)

**Comment by BernhardPosselt** [comment]
I'm merging this now and someone else should improve the icon ;)

**Pull request merged**
