### PR TITLE
Added vk.com video to HTMLPurifier SafeIframe

### PR DESCRIPTION
**Pull request by rakshazi**
Example of video link: https://vk.com/video_ext.php?oid=-67429455&id=171494363&hash=6fdc6b4472acdaa7

PS: I added this pull request according following message: https://github.com/owncloud/news/issues/344#issuecomment-24386232

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Did you test this? Does it work? IIRC you also need to add it to picofee https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Filter/Attribute.php#L125

**Comment by rakshazi** [comment]
Some of videos work, but not all. Sorry, but i'm bad in regex. Here is iframe of real video:
```html
<iframe allowfullscreen="" width="607" height="360" src="https://vk.com/video_ext.php?oid=-67429455&id=171494363&hash=6fdc6b4472acdaa7" frameborder="0"></iframe>
```

**Comment by rakshazi** [comment]
I'll add PR to PicoFeed now.

**Comment by rakshazi** [comment]
Here is PR to PicoFeed: https://github.com/fguillot/picoFeed/pull/240

**Comment by rakshazi** [comment]
@BernhardPosselt tell me, please, when new News release (with these changes) will be available?

**Comment by BernhardPosselt** [comment]
I still need to sync with picoFeed ;)

Probably this weekend

**Comment by rakshazi** [comment]
@BernhardPosselt thank you!

**Pull request merged**
